//! Rendering merged domain descriptions as Rust source.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use anyhow::{Context, Result, bail};

use super::merge::MergedDomain;
use super::naming;
use super::schema::{Command, Event, Property, TypeDef};

/// Domain name → the type ids it declares. Used to resolve and validate `$ref`.
pub type Index = BTreeMap<String, Vec<String>>;

/// Fields that must be `Box`ed because their type participates in a reference
/// cycle. Keyed by `("Domain.TypeId", "wireFieldName")`.
///
/// Five exist at the pinned ref (`Console.StackTrace.parentStackTrace`,
/// `DOM.Node.contentDocument`, `DOM.Node.templateContent`,
/// `Runtime.RemoteObject.classPrototype`,
/// `Runtime.StructureDescription.prototypeStructure`) but the set is computed
/// rather than listed, so a newly-recursive type is handled instead of
/// producing an `E0072` in generated code.
pub type BoxedFields = BTreeSet<(String, String)>;

/// Find every field that would give its struct infinite size.
///
/// Only *direct* references can do that: a `Vec<T>` is already heap-allocated,
/// so an array field breaks a cycle by itself and is not an edge here.
pub fn analyse_cycles(domains: &[MergedDomain]) -> BoxedFields {
    // "Domain.TypeId" → the types its direct fields refer to.
    let mut edges: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    for d in domains {
        for t in &d.types {
            if t.ty != "object" {
                continue;
            }
            let from = format!("{}.{}", d.name, t.id);
            for prop in &t.properties {
                // An inline enum is a leaf; an array is already indirect.
                if prop.enum_values.is_some() || prop.ty.as_deref() == Some("array") {
                    continue;
                }
                let Some(reference) = &prop.reference else {
                    continue;
                };
                if primitive(reference).is_some() {
                    continue;
                }
                let to = match reference.split_once('.') {
                    Some(_) => reference.clone(),
                    None => format!("{}.{reference}", d.name),
                };
                let field = prop.name.clone().unwrap_or_default();
                edges.entry(from.clone()).or_default().push((to, field));
            }
        }
    }

    let mut boxed = BoxedFields::new();
    for (from, targets) in &edges {
        for (to, field) in targets {
            if reaches(&edges, to, from) {
                boxed.insert((from.clone(), field.clone()));
            }
        }
    }
    boxed
}

/// Whether `goal` is reachable from `start` by following direct field edges.
fn reaches(edges: &BTreeMap<String, Vec<(String, String)>>, start: &str, goal: &str) -> bool {
    let mut stack = vec![start.to_owned()];
    let mut seen = BTreeSet::new();

    while let Some(node) = stack.pop() {
        if node == goal {
            return true;
        }
        if !seen.insert(node.clone()) {
            continue;
        }
        if let Some(next) = edges.get(&node) {
            stack.extend(next.iter().map(|(to, _)| to.clone()));
        }
    }
    false
}

const HEADER: &str = "\
// @generated by `cargo run -p xtask -- codegen`. DO NOT EDIT BY HAND.
//
// Regenerate after updating `reference/webkit-protocol/` (git-ignored; see
// reference/README.md). `cargo run -p xtask -- verify-protocol` checks this
// output against the protocol the installed WebKit actually exposes.
";

/// An enum synthesised for an anonymous `enum` on a property.
struct InlineEnum {
    name: String,
    values: Vec<String>,
    owner: String,
}

struct Ctx<'a> {
    domain: &'a str,
    module: String,
    index: &'a Index,
    boxed: &'a BoxedFields,
    inline: Vec<InlineEnum>,
}

impl Ctx<'_> {
    /// Absolute path to an item in this domain's module.
    ///
    /// Always absolute, so the same string is valid at the module root and
    /// inside the nested `commands` / `events` modules.
    fn local(&self, name: &str) -> String {
        format!("crate::generated::{}::{}", self.module, name)
    }

    fn push_inline(&mut self, name: String, values: &[String], owner: &str) {
        if !self.inline.iter().any(|e| e.name == name) {
            self.inline.push(InlineEnum {
                name,
                values: values.to_vec(),
                owner: owner.to_owned(),
            });
        }
    }
}

/// Render one domain module.
pub fn domain(d: &MergedDomain, index: &Index, boxed: &BoxedFields) -> Result<String> {
    let mut ctx = Ctx {
        domain: &d.name,
        module: naming::module_ident(&d.name),
        index,
        boxed,
        inline: Vec::new(),
    };

    let types = render_types(&d.types, &mut ctx)
        .with_context(|| format!("rendering types of domain {}", d.name))?;
    let commands = render_commands(&d.commands, &mut ctx)
        .with_context(|| format!("rendering commands of domain {}", d.name))?;
    let events = render_events(&d.events, &mut ctx)
        .with_context(|| format!("rendering events of domain {}", d.name))?;
    // Rendered last: inline enums are discovered while rendering everything else.
    let inline = render_inline_enums(&ctx);

    let mut out = String::with_capacity(16 * 1024);
    out.push_str(HEADER);
    out.push('\n');
    writeln!(out, "//! The `{}` domain.", d.name)?;
    if let Some(desc) = &d.description {
        out.push_str("//!\n");
        for line in doc_text(desc).lines() {
            writeln!(out, "//! {line}")?;
        }
    }
    out.push_str("//!\n");
    writeln!(
        out,
        "//! Debuggable types: {}",
        list_or_none(&d.debuggable_types)
    )?;
    writeln!(out, "//! Target types: {}", list_or_none(&d.target_types))?;
    out.push('\n');
    // A domain whose types are all aliases derives nothing at the module root,
    // and an unused import is a warning that `-D warnings` turns into a build
    // failure. The nested `commands`/`events` modules import for themselves, so
    // they are deliberately not considered here.
    if [&types, &inline].iter().any(|s| s.contains("derive(")) {
        out.push_str("use serde::{Deserialize, Serialize};\n\n");
    }

    out.push_str(&types);
    out.push_str(&inline);
    out.push_str(&commands);
    out.push_str(&events);
    Ok(out)
}

fn list_or_none(items: &[String]) -> String {
    if items.is_empty() {
        "none declared".into()
    } else {
        items
            .iter()
            .map(|s| format!("`{s}`"))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

// ---------------------------------------------------------------- types ----

fn render_types(types: &[TypeDef], ctx: &mut Ctx<'_>) -> Result<String> {
    let mut out = String::new();
    for t in types {
        let docs = type_docs(t);
        match (
            t.ty.as_str(),
            t.enum_values.as_ref(),
            t.properties.is_empty(),
        ) {
            // A closed set of string values.
            ("string", Some(values), _) => {
                out.push_str(&render_enum(&t.id, &docs, values));
            }
            // An object with a known shape.
            ("object", _, false) => {
                let key = format!("{}.{}", ctx.domain, t.id);
                out.push_str(&render_struct(
                    &t.id,
                    &docs,
                    &t.properties,
                    &t.id,
                    Some(&key),
                    ctx,
                )?);
            }
            // An object with no declared shape is genuinely free-form.
            ("object", _, true) => {
                out.push_str(&docs);
                writeln!(out, "pub type {} = serde_json::Value;\n", t.id)?;
            }
            ("array", ..) => {
                let items = t
                    .items
                    .as_ref()
                    .with_context(|| format!("array type `{}` has no items", t.id))?;
                let inner = rust_type(items, &t.id, ctx)?;
                out.push_str(&docs);
                writeln!(out, "pub type {} = Vec<{inner}>;\n", t.id)?;
            }
            (prim, ..) => {
                let inner = primitive(prim)
                    .with_context(|| format!("type `{}` has unknown kind `{prim}`", t.id))?;
                out.push_str(&docs);
                writeln!(out, "pub type {} = {inner};\n", t.id)?;
            }
        }
    }
    Ok(out)
}

fn render_inline_enums(ctx: &Ctx<'_>) -> String {
    let mut out = String::new();
    for e in &ctx.inline {
        let docs = format!(
            "/// The values `{}` accepts.\n///\n/// Synthesised: the protocol declares this set inline rather than naming it.\n",
            e.owner
        );
        out.push_str(&render_enum(&e.name, &docs, &e.values));
    }
    out
}

fn render_enum(name: &str, docs: &str, values: &[String]) -> String {
    let mut out = String::new();
    out.push_str(docs);
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    let _ = writeln!(out, "pub enum {name} {{");
    let mut emitted: Vec<String> = Vec::new();
    for value in values {
        let mut variant = naming::variant_ident(value);
        // Two wire tokens can camel-case to the same identifier; keep both
        // reachable rather than dropping one silently.
        while emitted.contains(&variant) {
            variant.push('_');
        }
        emitted.push(variant.clone());
        let _ = writeln!(out, "    #[serde(rename = {value:?})]");
        let _ = writeln!(out, "    {variant},");
    }
    out.push_str("}\n\n");
    out
}

fn render_struct(
    name: &str,
    docs: &str,
    props: &[Property],
    owner: &str,
    // `Some("Domain.TypeId")` for a declared type, `None` for a command or
    // event struct — those are never referenced, so never recursive.
    type_key: Option<&str>,
    ctx: &mut Ctx<'_>,
) -> Result<String> {
    let mut out = String::new();
    out.push_str(docs);
    out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    if props.is_empty() {
        // Braces, not a unit struct: a unit struct serialises to `null`, and
        // the protocol expects `{}` for a parameterless command.
        writeln!(out, "pub struct {name} {{}}\n")?;
        return Ok(out);
    }
    writeln!(out, "pub struct {name} {{")?;
    for prop in props {
        let wire = prop
            .name
            .as_deref()
            .with_context(|| format!("property of `{name}` has no name"))?;
        let ident = naming::field_ident(wire);
        let mut ty = rust_type(prop, owner, ctx)?;

        if let Some(desc) = &prop.description {
            for line in doc_text(desc).lines() {
                writeln!(out, "    /// {line}")?;
            }
        }

        // A field whose type can reach back to this struct must be indirect,
        // or the struct has no finite size.
        if let Some(key) = type_key
            && ctx.boxed.contains(&(key.to_owned(), wire.to_owned()))
        {
            ty = format!("Box<{ty}>");
        }

        let mut attrs: Vec<String> = Vec::new();
        // Emit a rename only when the Rust spelling differs from the wire one.
        if ident.trim_start_matches("r#") != wire {
            attrs.push(format!("rename = {wire:?}"));
        }
        if prop.optional {
            ty = format!("Option<{ty}>");
            attrs.push("default".into());
            attrs.push("skip_serializing_if = \"Option::is_none\"".into());
        }
        if !attrs.is_empty() {
            writeln!(out, "    #[serde({})]", attrs.join(", "))?;
        }
        writeln!(out, "    pub {ident}: {ty},")?;
    }
    out.push_str("}\n\n");
    Ok(out)
}

// ------------------------------------------------------- commands/events ----

fn render_commands(commands: &[Command], ctx: &mut Ctx<'_>) -> Result<String> {
    if commands.is_empty() {
        return Ok(String::new());
    }
    let variant = naming::type_ident(ctx.domain);
    let mut body = String::new();

    for c in commands {
        let name = naming::type_ident(&c.name);
        let docs = member_docs(
            c.description.as_deref(),
            c.condition.as_deref(),
            &c.target_types,
        );
        body.push_str(&render_struct(
            &name,
            &docs,
            &c.parameters,
            &c.name,
            None,
            ctx,
        )?);

        let returns = if c.returns.is_empty() {
            "crate::generated::Empty".to_string()
        } else {
            let rname = format!("{name}Returns");
            let rdocs = format!("/// What `{}.{}` replies with.\n", ctx.domain, c.name);
            body.push_str(&render_struct(
                &rname, &rdocs, &c.returns, &c.name, None, ctx,
            )?);
            rname
        };

        writeln!(body, "impl crate::Command for {name} {{")?;
        writeln!(
            body,
            "    const DOMAIN: crate::Domain = crate::Domain::{variant};"
        )?;
        writeln!(body, "    const METHOD: &'static str = {:?};", c.name)?;
        writeln!(body, "    type Returns = {returns};")?;
        body.push_str("}\n\n");
    }

    Ok(wrap_module(
        "commands",
        &format!(
            "Requests the debugger can send to a `{}` debuggee.",
            ctx.domain
        ),
        &body,
    ))
}

fn render_events(events: &[Event], ctx: &mut Ctx<'_>) -> Result<String> {
    if events.is_empty() {
        return Ok(String::new());
    }
    let variant = naming::type_ident(ctx.domain);
    let mut body = String::new();

    for e in events {
        let name = naming::type_ident(&e.name);
        let docs = member_docs(
            e.description.as_deref(),
            e.condition.as_deref(),
            &e.target_types,
        );
        body.push_str(&render_struct(
            &name,
            &docs,
            &e.parameters,
            &e.name,
            None,
            ctx,
        )?);
        writeln!(body, "impl crate::Event for {name} {{")?;
        writeln!(
            body,
            "    const DOMAIN: crate::Domain = crate::Domain::{variant};"
        )?;
        writeln!(body, "    const METHOD: &'static str = {:?};", e.name)?;
        body.push_str("}\n\n");
    }

    Ok(wrap_module(
        "events",
        &format!("Messages a `{}` debuggee sends unprompted.", ctx.domain),
        &body,
    ))
}

fn wrap_module(name: &str, doc: &str, body: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "/// {doc}");
    let _ = writeln!(out, "pub mod {name} {{");
    if body.contains("derive(") {
        out.push_str("    use serde::{Deserialize, Serialize};\n\n");
    }
    for line in body.lines() {
        if line.is_empty() {
            out.push('\n');
        } else {
            let _ = writeln!(out, "    {line}");
        }
    }
    out.push_str("}\n\n");
    out
}

// ------------------------------------------------------------ type rules ----

fn primitive(kind: &str) -> Option<&'static str> {
    Some(match kind {
        "string" => "String",
        // The protocol's `integer` is a signed 32-bit value in practice, but
        // `i64` costs nothing and cannot overflow on a hostile debuggee.
        "integer" => "i64",
        "number" => "f64",
        "boolean" => "bool",
        // `any` and shapeless `object` are genuinely arbitrary JSON.
        "any" | "object" => "serde_json::Value",
        _ => return None,
    })
}

fn rust_type(prop: &Property, owner: &str, ctx: &mut Ctx<'_>) -> Result<String> {
    // An inline `enum` wins over the bare `type: "string"` it sits alongside.
    if let Some(values) = &prop.enum_values {
        let field = prop.name.as_deref().unwrap_or("value");
        let name = naming::inline_enum_ident(owner, field);
        ctx.push_inline(name.clone(), values, &format!("{}.{owner}", ctx.domain));
        return Ok(ctx.local(&name));
    }

    if let Some(reference) = &prop.reference {
        return resolve_ref(reference, ctx);
    }

    match prop.ty.as_deref() {
        Some("array") => {
            let items = prop
                .items
                .as_ref()
                .context("array property has no `items`")?;
            Ok(format!("Vec<{}>", rust_type(items, owner, ctx)?))
        }
        Some(kind) => primitive(kind)
            .map(str::to_owned)
            .with_context(|| format!("unknown property kind `{kind}`")),
        None => bail!("property has neither `type` nor `$ref`"),
    }
}

/// Resolve a `$ref`, verifying the target actually exists.
///
/// A dangling reference would otherwise become Rust that fails to compile with
/// a message pointing at generated code rather than at the protocol.
fn resolve_ref(reference: &str, ctx: &Ctx<'_>) -> Result<String> {
    // Upstream occasionally writes `"$ref": "boolean"` where it means
    // `"type": "boolean"` — `Runtime.PropertyDescriptor.isPrivate` does exactly
    // this at the pinned ref. Treat a reference naming a primitive as that
    // primitive rather than failing on a typo we cannot fix from here.
    if let Some(prim) = primitive(reference) {
        return Ok(prim.to_owned());
    }

    let (domain, id) = match reference.split_once('.') {
        Some((d, i)) => (d, i),
        None => (ctx.domain, reference),
    };

    let known = ctx
        .index
        .get(domain)
        .with_context(|| format!("`{reference}` names domain `{domain}`, which was not loaded"))?;
    if !known.iter().any(|t| t == id) {
        bail!("`{reference}` names type `{id}`, which domain `{domain}` does not declare");
    }

    Ok(format!(
        "crate::generated::{}::{id}",
        naming::module_ident(domain)
    ))
}

// ------------------------------------------------------------------ docs ----

fn type_docs(t: &TypeDef) -> String {
    member_docs(t.description.as_deref(), t.condition.as_deref(), &[])
}

fn member_docs(description: Option<&str>, condition: Option<&str>, targets: &[String]) -> String {
    let mut out = String::new();
    match description {
        Some(desc) => {
            for line in doc_text(desc).lines() {
                let _ = writeln!(out, "/// {line}");
            }
        }
        None => out.push_str("/// Undocumented upstream.\n"),
    }
    // A member can be narrower than its domain. Surfacing it here is what lets
    // a panel know a command exists only for, say, page targets, rather than
    // discovering it by getting an error back.
    if !targets.is_empty() {
        out.push_str("///\n");
        let _ = writeln!(
            out,
            "/// Available on target types: {}",
            list_or_none(targets)
        );
    }
    if let Some(cond) = condition {
        out.push_str("///\n");
        out.push_str(
            "/// Merged from platform-conditional variants; fields absent from one\n\
             /// variant are optional here. Conditions:\n",
        );
        let _ = writeln!(out, "/// `{}`", cond.replace('\n', " "));
    }
    out
}

/// Make an upstream description safe and readable as rustdoc.
///
/// Upstream text is HTML: `<code>locations</code>`, occasional `<br>`. Left as
/// is, rustdoc warns about unclosed tags and treats `[x]` as a broken
/// intra-doc link, which `-D warnings` then turns into a build failure.
fn doc_text(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    let mut chars = raw.chars().peekable();
    let mut tag = String::new();

    while let Some(c) = chars.next() {
        match c {
            '<' => {
                tag.clear();
                for t in chars.by_ref() {
                    if t == '>' {
                        break;
                    }
                    tag.push(t);
                }
                // Render code spans as rustdoc code, drop every other tag.
                if tag.eq_ignore_ascii_case("code") || tag.eq_ignore_ascii_case("/code") {
                    out.push('`');
                }
            }
            // Square brackets read as intra-doc links; escape them.
            '[' | ']' => {
                out.push('\\');
                out.push(c);
            }
            _ => out.push(c),
        }
    }
    out.trim().to_owned()
}

// -------------------------------------------------------------- mod.rs ----

/// Render the `generated/mod.rs` that declares every domain module.
pub fn mod_rs(modules: &[(String, String, Option<String>)]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(
        "\n\
//! Generated protocol domains.\n\
//!\n\
//! One module per domain. Types sit at each module's root because that is how\n\
//! cross-domain references address them; commands and events have their own\n\
//! namespaces so a type and a same-named event cannot collide.\n\
//!\n\
//! ```text\n\
//! generated::debugger::Location            // a type\n\
//! generated::debugger::commands::Resume    // a command\n\
//! generated::debugger::events::Paused      // an event\n\
//! ```\n\
\n\
use serde::{Deserialize, Serialize};\n\
\n",
    );

    for (module, domain, desc) in modules {
        if let Some(d) = desc {
            let first = doc_text(d).lines().next().unwrap_or_default().to_owned();
            if !first.is_empty() {
                let _ = writeln!(out, "/// `{domain}` — {first}");
            } else {
                let _ = writeln!(out, "/// The `{domain}` domain.");
            }
        } else {
            let _ = writeln!(out, "/// The `{domain}` domain.");
        }
        let _ = writeln!(out, "pub mod {module};");
    }

    out.push_str(
        "\n\
/// The reply of a command that returns nothing.\n\
///\n\
/// Deserialises from anything, because a debuggee may answer a void command\n\
/// with `{}`, with `null`, or with no `result` member at all — all three occur.\n\
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize)]\n\
pub struct Empty;\n\
\n\
impl<'de> Deserialize<'de> for Empty {\n\
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {\n\
        serde::de::IgnoredAny::deserialize(d)?;\n\
        Ok(Empty)\n\
    }\n\
}\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn code_tags_become_backticks_and_other_tags_vanish() {
        assert_eq!(
            doc_text("returned in <code>locations</code>.<br>Done."),
            "returned in `locations`.Done."
        );
    }

    #[test]
    fn square_brackets_are_escaped_so_rustdoc_sees_no_broken_link() {
        // Unescaped, `-D warnings` fails the build on a broken intra-doc link.
        // Raw strings here: the point is the literal characters, and ordinary
        // escapes make it impossible to see what is being asserted.
        assert_eq!(doc_text(r"see [Foo]"), r"see \[Foo\]");
        assert_eq!(doc_text(r"an array [1,2]"), r"an array \[1,2\]");
    }

    #[test]
    fn a_parameterless_command_serialises_as_an_object_not_null() {
        let mut index = Index::new();
        index.insert("Debugger".into(), vec![]);
        let boxed = BoxedFields::new();
        let mut ctx = Ctx {
            domain: "Debugger",
            module: "debugger".into(),
            index: &index,
            boxed: &boxed,
            inline: vec![],
        };
        let src = render_struct("Resume", "/// x\n", &[], "resume", None, &mut ctx).unwrap();
        assert!(src.contains("pub struct Resume {}"), "got: {src}");
    }

    #[test]
    fn colliding_enum_variants_are_kept_distinct() {
        // Two wire tokens can camel-case identically; dropping one would make
        // a value silently undeserialisable.
        let src = render_enum("E", "", &["foo-bar".to_string(), "fooBar".to_string()]);
        assert!(src.contains("FooBar,"));
        assert!(src.contains("FooBar_,"));
        assert!(src.contains(r#"rename = "foo-bar""#));
        assert!(src.contains(r#"rename = "fooBar""#));
    }

    #[test]
    fn a_dangling_reference_is_an_error_not_broken_rust() {
        let mut index = Index::new();
        index.insert("Debugger".into(), vec!["Location".into()]);
        let boxed = BoxedFields::new();
        let ctx = Ctx {
            domain: "Debugger",
            module: "debugger".into(),
            index: &index,
            boxed: &boxed,
            inline: vec![],
        };
        assert!(resolve_ref("Location", &ctx).is_ok());
        assert!(resolve_ref("Nonexistent", &ctx).is_err());
        assert!(resolve_ref("NoSuchDomain.Thing", &ctx).is_err());
    }

    #[test]
    fn references_resolve_to_absolute_paths() {
        // Absolute, so the same string works at the module root and inside the
        // nested `commands` / `events` modules.
        let mut index = Index::new();
        index.insert("DOM".into(), vec!["NodeId".into()]);
        index.insert("Debugger".into(), vec![]);
        let boxed = BoxedFields::new();
        let ctx = Ctx {
            domain: "Debugger",
            module: "debugger".into(),
            index: &index,
            boxed: &boxed,
            inline: vec![],
        };
        assert_eq!(
            resolve_ref("DOM.NodeId", &ctx).unwrap(),
            "crate::generated::dom::NodeId"
        );
    }
}
